services:
  typephp:
    image: ${TYPEPHP_IMAGE:-ghcr.io/roiwk/typephp-docker:0.9.4}
    pull_policy: ${TYPEPHP_PULL:-missing}
    working_dir: /src
    volumes:
      - ${SRC:-.}:/src
    environment:
      PHP_HOME: /opt/php
      PHPX_HOME: /opt/phpx
      # shared | static | php-builder
      TYPEPHP_LINK: ${TYPEPHP_LINK:-shared}
      TYPEPHP_JOBS: ${TYPEPHP_JOBS:-2}
      TYPEPHP_ZTS: ${TYPEPHP_ZTS:-on}
      TYPEPHP_SAPI: ${TYPEPHP_SAPI:-embed}
      TYPEPHP_EXTENSIONS: ${TYPEPHP_EXTENSIONS:-}
