#!/usr/bin/env bash
# Rewrite versions.env from GitHub releases.
# Usage: scripts/sync-release.sh [v0.9.4|latest]
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
requested="${1:-latest}"
php_minor="${TYPEPHP_PHP_MINOR:-8.4}"

python3 - "${root}" "${requested}" "${php_minor}" << 'PY'
import hashlib, json, sys, urllib.request
from pathlib import Path

root, requested, php_minor = sys.argv[1:]

def get(url):
    req = urllib.request.Request(
        url,
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "typephp-docker",
        },
    )
    with urllib.request.urlopen(req, timeout=120) as response:
        return json.load(response)

def sha256_file(url):
    req = urllib.request.Request(url, headers={"User-Agent": "typephp-docker"})
    digest = hashlib.sha256()
    with urllib.request.urlopen(req, timeout=300) as response:
        while True:
            chunk = response.read(1024 * 1024)
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()

if requested == "latest":
    release = get("https://api.github.com/repos/swoole/typephp/releases/latest")
else:
    release = get(f"https://api.github.com/repos/swoole/typephp/releases/tags/{requested}")

version = release["tag_name"]
published = release["published_at"]
checksums = {}
php_version = None
for asset in release["assets"]:
    name = asset["name"]
    prefix = f"tpc_{version}_linux_"
    marker = f"_php{php_minor}."
    if not name.startswith(prefix) or marker not in name or not name.endswith("-zts.tar.gz"):
        continue
    platform = name[len(prefix):].split("_php", 1)[0]
    if platform not in ("x64", "arm64"):
        continue
    found = name.split("_php", 1)[1].split("-zts.tar.gz", 1)[0]
    if php_version is None:
        php_version = found
    elif found != php_version:
        raise SystemExit(f"mixed PHP versions in {version}: {php_version} and {found}")
    digest = asset.get("digest") or ""
    if not digest.startswith("sha256:"):
        raise SystemExit(f"missing sha256 digest for {name}")
    checksums[platform] = digest.split(":", 1)[1]

if php_version is None or "x64" not in checksums or "arm64" not in checksums:
    raise SystemExit(f"no linux PHP {php_minor} tpc assets on {version}")

def commit_at(repo):
    commits = get(
        f"https://api.github.com/repos/{repo}/commits?until={published}&per_page=1"
    )
    if not commits:
        raise SystemExit(f"no {repo} commit before {published}")
    return commits[0]["sha"]

phpx_ref = commit_at("swoole/phpx")
phpy_ref = commit_at("swoole/phpy")

releases = get("https://api.github.com/repos/swoole/phpx/releases?per_page=20")
sdk = None
for item in releases:
    if item.get("published_at") and item["published_at"] > published:
        continue
    found = {}
    sdk_php = None
    for asset in item["assets"]:
        name = asset["name"]
        if not name.startswith("phpx-sdk_") or not name.endswith(".tar.xz"):
            continue
        if "_linux-x64.tar.xz" in name:
            platform = "x64"
        elif "_linux-arm64.tar.xz" in name:
            platform = "arm64"
        else:
            continue
        # phpx-sdk_v2.9.3_php8.4.25_linux-x64.tar.xz
        body = name[len("phpx-sdk_"):]
        sdk_version, rest = body.split("_php", 1)
        this_php = rest.split("_linux-", 1)[0]
        if sdk_php is None:
            sdk_php = this_php
        elif this_php != sdk_php:
            continue
        digest = asset.get("digest") or ""
        if not digest.startswith("sha256:"):
            continue
        found[platform] = digest.split(":", 1)[1]
    if "x64" in found and "arm64" in found:
        sdk = {
            "version": item["tag_name"],
            "php": sdk_php,
            "x64": found["x64"],
            "arm64": found["arm64"],
        }
        break

if sdk is None:
    raise SystemExit(f"no PHPX linux SDK release at or before {published}")

print(f"hashing php-{php_version}.tar.xz", file=sys.stderr)
php_sha = sha256_file(f"https://www.php.net/distributions/php-{php_version}.tar.xz")

text = f"""# Generated by scripts/sync-release.sh for {version} ({published}).
# Dynamic tpc is linked against PHP_VERSION. --full-static links PHPX_SDK_*.

TYPEPHP_VERSION={version}
PHP_VERSION={php_version}
PHP_SHA256={php_sha}

TPC_SHA256_X64={checksums['x64']}
TPC_SHA256_ARM64={checksums['arm64']}

PHPX_REF={phpx_ref}
PHPY_REF={phpy_ref}

PHPX_SDK_VERSION={sdk['version']}
PHPX_SDK_PHP={sdk['php']}
PHPX_SDK_SHA256_X64={sdk['x64']}
PHPX_SDK_SHA256_ARM64={sdk['arm64']}
"""
Path(root, "versions.env").write_text(text)
print(text, end="")
PY
